# Generated by Django 4.1.5 on 2023-12-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penerima', '0003_alter_ranking_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='status',
            field=models.CharField(choices=[('Diranking', 'Diranking'), ('Belum Diverifikasi', 'Belum Diverifikasi'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak'), ('Penerima', 'Penerima')], default='Diranking', max_length=20),
        ),
    ]
