# Generated by Django 4.2.1 on 2023-11-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtks', '0002_alter_kondisi_rumah_luas_lahan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kondisi_rumah',
            name='luas_lahan',
            field=models.IntegerField(),
        ),
    ]
