# Generated by Django 4.1.5 on 2023-12-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kriteria',
            name='tahun',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
